spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llava
      embedding:
        enabled: false

kakao:
  rest-api-key: "카카오_REST_API_KEY"
  javascript-key: "카카오_JAVASCRIPT_KEY"