spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5
      embedding:
        enabled: false

kakao:
  rest-api-key: "5da993ee1c0a9bd4a5496c5b3f713d6f"
  javascript-key: "a68d3e22f39309351a674b46634e320c"